
package mx.com.mtlsa.billing.client.cancelaciones;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSCFDICancelacion", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://edixcfdisecure.ekomercio.com/Cliente_SAT_CFDI_Web/Servicios/WSCFDICancelacion.asmx?WSDL")
public class WSCFDICancelacion
    extends Service
{

    private final static URL WSCFDICANCELACION_WSDL_LOCATION;
    private final static WebServiceException WSCFDICANCELACION_EXCEPTION;
    private final static QName WSCFDICANCELACION_QNAME = new QName("http://tempuri.org/", "WSCFDICancelacion");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://edixcfdisecure.ekomercio.com/Cliente_SAT_CFDI_Web/Servicios/WSCFDICancelacion.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSCFDICANCELACION_WSDL_LOCATION = url;
        WSCFDICANCELACION_EXCEPTION = e;
    }

    public WSCFDICancelacion() {
        super(__getWsdlLocation(), WSCFDICANCELACION_QNAME);
    }

    public WSCFDICancelacion(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSCFDICANCELACION_QNAME, features);
    }

    public WSCFDICancelacion(URL wsdlLocation) {
        super(wsdlLocation, WSCFDICANCELACION_QNAME);
    }

    public WSCFDICancelacion(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSCFDICANCELACION_QNAME, features);
    }

    public WSCFDICancelacion(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSCFDICancelacion(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSCFDICancelacionSoap
     */
    @WebEndpoint(name = "WSCFDICancelacionSoap")
    public WSCFDICancelacionSoap getWSCFDICancelacionSoap() {
        return super.getPort(new QName("http://tempuri.org/", "WSCFDICancelacionSoap"), WSCFDICancelacionSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSCFDICancelacionSoap
     */
    @WebEndpoint(name = "WSCFDICancelacionSoap")
    public WSCFDICancelacionSoap getWSCFDICancelacionSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WSCFDICancelacionSoap"), WSCFDICancelacionSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSCFDICANCELACION_EXCEPTION!= null) {
            throw WSCFDICANCELACION_EXCEPTION;
        }
        return WSCFDICANCELACION_WSDL_LOCATION;
    }

}
