package mx.com.mtlsa.billing.utils.plantillas;

public class CancelaRechazoBuzon {
	
	public String plantillaRechazoBuzon(String razonSocial , String uuid) {
		StringBuilder template = new StringBuilder();
		
		template.append("<div>");
		template.append("   <style>");
		template.append("      <!--");
		template.append("         @font-face");
		template.append("         	{font-family:Wingdings}");
		template.append("         @font-face");
		template.append("         	{font-family:'Cambria Math'}");
		template.append("         @font-face");
		template.append("         	{font-family:Calibri}");
		template.append("         @font-face");
		template.append("         	{font-family:Roboto}");
		template.append("         .rps_2229 p.x_MsoNormal, .rps_2229 li.x_MsoNormal, .rps_2229 div.x_MsoNormal");
		template.append("         	{margin:0cm;");
		template.append("         	margin-bottom:.0001pt;");
		template.append("         	font-size:10.0pt;");
		template.append("         	font-family:'Calibri',sans-serif}");
		template.append("         .rps_2229 a:link, .rps_2229 span.x_MsoHyperlink");
		template.append("         	{color:blue;");
		template.append("         	text-decoration:underline}");
		template.append("         .rps_2229 a:visited, .rps_2229 span.x_MsoHyperlinkFollowed");
		template.append("         	{color:purple;");
		template.append("         	text-decoration:underline}");
		template.append("         .rps_2229 p.x_MsoListParagraph, .rps_2229 li.x_MsoListParagraph, .rps_2229 div.x_MsoListParagraph");
		template.append("         	{margin-top:0cm;");
		template.append("         	margin-right:0cm;");
		template.append("         	margin-bottom:0cm;");
		template.append("         	margin-left:36.0pt;");
		template.append("         	margin-bottom:.0001pt;");
		template.append("         	font-size:10.0pt;");
		template.append("         	font-family:'Calibri',sans-serif}");
		template.append("         .rps_2229 p.x_msonormal0, .rps_2229 li.x_msonormal0, .rps_2229 div.x_msonormal0");
		template.append("         	{margin-right:0cm;");
		template.append("         	margin-left:0cm;");
		template.append("         	font-size:10.0pt;");
		template.append("         	font-family:'Calibri',sans-serif}");
		template.append("         .rps_2229 span.x_EmailStyle19");
		template.append("         	{font-family:'Arial',sans-serif;");
		template.append("         	color:black;");
		template.append("         	font-weight:normal;");
		template.append("         	font-style:normal;");
		template.append("         	text-decoration:none none}");
		template.append("         .rps_2229 span.x_EmailStyle20");
		template.append("         	{font-family:'Arial',sans-serif;");
		template.append("         	color:black;");
		template.append("         	font-weight:normal;");
		template.append("         	font-style:normal;");
		template.append("         	text-decoration:none none}");
		template.append("         .rps_2229 .x_MsoChpDefault");
		template.append("         	{font-size:10.0pt}");
		template.append("         @page WordSection1");
		template.append("         	{margin:72.0pt 72.0pt 72.0pt 72.0pt}");
		template.append("         .rps_2229 div.x_WordSection1");
		template.append("         	{}");
		template.append("         .rps_2229 ol");
		template.append("         	{margin-bottom:0cm}");
		template.append("         .rps_2229 ul");
		template.append("         	{margin-bottom:0cm}");
		template.append("        -->");
		template.append("   </style>");
		template.append("   <div class='rps_2229'>");
		template.append("      <div lang='es-419' link='blue' vlink='purple'>");
		template.append("         <div class='x_WordSection1'>");
		template.append("            <table class='x_MsoNormalTable' border='0' cellspacing='0' cellpadding='0' width='100%' style='width:100.0%; border-collapse:collapse'>");
		template.append("               <tbody>");
		template.append("                  <tr>");
		template.append("                     <td valign='top' style='padding:1.5pt 0cm 20.25pt 0cm'>");
		template.append("                        <p class='x_MsoNormal'><b><span style='font-size:18.0pt; font-family:Roboto; color:#C3CED9'><img data-imagetype='External' src='https://cloud.metalsa.com/IFP/resources/img/logo_color.png' width='200' height='53' id='x__x0000_i1025' style='width:2.0833in; height:.5486in'></span></b></p>");
		template.append("                     </td>");
		template.append("                  </tr>");
		template.append("              </tbody>");
		template.append("            </table>");
		template.append("            <p class='x_MsoNormal'><span style='display:none'>&nbsp;</span></p>");
		template.append("            <table class='x_MsoNormalTable' border='0' cellspacing='0' cellpadding='0' width='100%' style='width:100.0%; background:#FAFAFA; border-collapse:collapse; border-spacing:0'>");
		template.append("               <tbody>");
		template.append("                  <tr>");
		template.append("                     <td valign='top' style='padding:0cm 0cm 0cm 0cm'>");
		template.append("                        <div>");
		template.append("                           <div>");
		template.append("                              <p class='x_MsoNormal' style='line-height:15.0pt'><span style='font-size:15.0pt'>&nbsp;</span></p>");
		template.append("                           </div>");
		template.append("                        </div>");
		template.append("                        <table class='x_MsoNormalTable' border='0' cellspacing='0' cellpadding='0' width='100%' style='width:100.0%; border-collapse:collapse; border-spacing:0'>");
		template.append("                           <tbody>");
		template.append("                              <tr>");
		template.append("                                 <td valign='top' style='padding:0cm 15.0pt 0cm 15.0pt; word-break:break-word; word-wrap:break-word'></td>");
		template.append("                              </tr>");
		template.append("                           </tbody>");
		template.append("                        </table>");
		template.append("                        <p class='x_MsoNormal'><span style='font-size:11.0pt; display:none'>&nbsp;</span></p>");
		template.append("                        <table class='x_MsoNormalTable' border='0' cellspacing='0' cellpadding='0' width='100%' style='width:100.0%; border-collapse:collapse; border-spacing:0'>");
		template.append("                           <tbody>");
		template.append("                              <tr>");
		template.append("                                 <td valign='top' style='padding:0cm 15.0pt 0cm 15.0pt; word-break:break-word; word-wrap:break-word'>");
		template.append("                                    <div>");
		template.append("                                       <p class='x_MsoNormal' style=''><span style='font-size:12.0pt; font-family:&quot;Arial&quot;,sans-serif'>&nbsp;<span style='color:black'>Se rechazo la solicitud de cancelación del proveedor <b>");
		template.append(razonSocial);
		template.append("</b> del CFDI con UUID <b>");
		template.append(uuid);
		template.append(" </b>, este CFDI se encuentra en proceso de trámite.</span></span></p>");
		template.append("                                    </div>");
		template.append("                                 </td>");
		template.append("                              </tr>");
		template.append("                           </tbody>");
		template.append("                        </table>");
		template.append("                        <p class='x_MsoNormal'><span style='font-size:12.0pt; font-family:&quot;Arial&quot;,sans-serif; display:none'>&nbsp;</span></p>");
		template.append("                        <table class='x_MsoNormalTable' border='0' cellspacing='0' cellpadding='0' width='100%' style='width:100.0%; border-collapse:collapse; border-spacing:0'>");
		template.append("                           <tbody>");
		template.append("                              <tr style='height:3.0pt'>");
		template.append("                                 <td valign='top' style='padding:0cm 15.0pt 0cm 15.0pt; height:3.0pt; word-break:break-word; word-wrap:break-word'>");
		template.append("                                    <div>");
		template.append("                                       <p class='x_MsoNormal' style=''><span style='font-size:12.0pt; font-family:&quot;Arial&quot;,sans-serif'>&nbsp;</span></p>");
		template.append("                                       <ul type='disc' style='margin-top:0cm'>");
		template.append("                                          <li class='x_MsoListParagraph' style='color:black; margin-left:0cm'><span style='font-size:12.0pt; font-family:&quot;Arial&quot;,sans-serif'>Para solicitar la cancelación requiere cancelar el tramite en Buzón.</span></li>");
		template.append("                                       </ul>");
		template.append("                                    </div>");
		template.append("                                 </td>");
		template.append("                              </tr>");
		template.append("                           </tbody>");
		template.append("                        </table>");
		template.append("                        <div>");
		template.append("                           <p class='x_MsoNormal' style='line-height:15.0pt'><span style='font-size:12.0pt; font-family:&quot;Arial&quot;,sans-serif; color:black'><img data-imagetype='External' src='https://cloud.metalsa.com/IFP/tk?kp=931575c5-27c8-4d20-9c9e-13216c8ed4cf' width='1' height='1' id='x__x0000_i1026' style='width:.0069in; height:.0069in'></span><span style='font-size:15.0pt'></span></p>");
		template.append("                        </div>");
		template.append("                     </td>");
		template.append("                  </tr>");
		template.append("               </tbody>");
		template.append("            </table>");
		template.append("          </div>");
		template.append("      </div>");
		template.append("   </div>");
		template.append(" </div>");
	    
		return template.toString();
		
		
	}

}
