
package mx.com.mtlsa.billing.client.edixcfdisecure;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSCFDBuilderPlus", targetNamespace = "http://edixcfdisecure.ekomercio.com/", wsdlLocation = "https://wstestrecepcionmetalsa.ekomercio.com/WSCFDIBuilderPlus/?wsdl")
public class WSCFDBuilderPlus
    extends Service
{

    private final static URL WSCFDBUILDERPLUS_WSDL_LOCATION;
    private final static WebServiceException WSCFDBUILDERPLUS_EXCEPTION;
    private final static QName WSCFDBUILDERPLUS_QNAME = new QName("http://edixcfdisecure.ekomercio.com/", "WSCFDBuilderPlus");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://wstestrecepcionmetalsa.ekomercio.com/WSCFDIBuilderPlus/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSCFDBUILDERPLUS_WSDL_LOCATION = url;
        WSCFDBUILDERPLUS_EXCEPTION = e;
    }

    public WSCFDBuilderPlus() {
        super(__getWsdlLocation(), WSCFDBUILDERPLUS_QNAME);
    }

    public WSCFDBuilderPlus(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSCFDBUILDERPLUS_QNAME, features);
    }

    public WSCFDBuilderPlus(URL wsdlLocation) {
        super(wsdlLocation, WSCFDBUILDERPLUS_QNAME);
    }

    public WSCFDBuilderPlus(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSCFDBUILDERPLUS_QNAME, features);
    }

    public WSCFDBuilderPlus(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSCFDBuilderPlus(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSCFDBuilderPlusSoap
     */
    @WebEndpoint(name = "WSCFDBuilderPlusSoap")
    public WSCFDBuilderPlusSoap getWSCFDBuilderPlusSoap() {
        return super.getPort(new QName("http://edixcfdisecure.ekomercio.com/", "WSCFDBuilderPlusSoap"), WSCFDBuilderPlusSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSCFDBuilderPlusSoap
     */
    @WebEndpoint(name = "WSCFDBuilderPlusSoap")
    public WSCFDBuilderPlusSoap getWSCFDBuilderPlusSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://edixcfdisecure.ekomercio.com/", "WSCFDBuilderPlusSoap"), WSCFDBuilderPlusSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSCFDBUILDERPLUS_EXCEPTION!= null) {
            throw WSCFDBUILDERPLUS_EXCEPTION;
        }
        return WSCFDBUILDERPLUS_WSDL_LOCATION;
    }

}
