
package mx.com.mtlsa.billing.client.edixcfdisecure;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSCFDBuilderPlusSoap", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSCFDBuilderPlusSoap {


    /**
     * Recupera el Xml del CFDI timbrado anteriormente en base al campo Misc30. Los parámetros son los siguientes: 
     * usuario: Usuario asignado para ingresar al WebService WSCFDBuilder.
     * password: Contraseña asignada para ingresar al WebService WSCFDBuilder.
     * id: Identificación fiscal de la empresa emisora del documento (RFC en México).
     * Misc30: Valor del campo 142 según layout 3.70 de EdixCFD.
     * 
     * @param password
     * @param misc30
     * @param usuario
     * @param id
     * @return
     *     returns mx.com.mtlsa.billing.client.edixcfdisecure.Result
     */
    @WebMethod(operationName = "RecuperarCFDIByMisc30", action = "http://edixcfdisecure.ekomercio.com/RecuperarCFDIByMisc30")
    @WebResult(name = "RecuperarCFDIByMisc30Result", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
    @RequestWrapper(localName = "RecuperarCFDIByMisc30", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.RecuperarCFDIByMisc30")
    @ResponseWrapper(localName = "RecuperarCFDIByMisc30Response", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.RecuperarCFDIByMisc30Response")
    public Result recuperarCFDIByMisc30(
        @WebParam(name = "usuario", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String usuario,
        @WebParam(name = "password", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String password,
        @WebParam(name = "id", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String id,
        @WebParam(name = "Misc30", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String misc30);

    /**
     * Valida y recibe un CFD ó CFDI con base en el xml UTF8 en la variable 'xmlFirmado'. Devuelve un acuse XML que indica el resultado. 
     * Los parámetros son los siguientes: 
     * usuario: Usuario asignado para ingresar al WebService WSCFDBuilder.
     * password: Contraseña asignada para ingresar al WebService WSCFDBuilder.
     * xmlFirmado: XML Firmado versión 2.x/3.x según el Anexo 20.
     * 
     * @param password
     * @param usuario
     * @param xmlFirmado
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ValidacionFacturasCFDI", action = "http://edixcfdisecure.ekomercio.com/ValidacionFacturasCFDI")
    @WebResult(name = "ValidacionFacturasCFDIResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
    @RequestWrapper(localName = "ValidacionFacturasCFDI", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.ValidacionFacturasCFDI")
    @ResponseWrapper(localName = "ValidacionFacturasCFDIResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.ValidacionFacturasCFDIResponse")
    public String validacionFacturasCFDI(
        @WebParam(name = "usuario", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String usuario,
        @WebParam(name = "password", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String password,
        @WebParam(name = "xmlFirmado", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String xmlFirmado);

    /**
     * Acerca de...
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://edixcfdisecure.ekomercio.com/about")
    @WebResult(name = "aboutResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
    @RequestWrapper(localName = "about", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.About")
    @ResponseWrapper(localName = "aboutResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.AboutResponse")
    public String about();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld", action = "http://edixcfdisecure.ekomercio.com/HelloWorld")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.HelloWorldResponse")
    public String helloWorld();

    /**
     * Genera una factura electrónica con base en el texto plano contenidoen la variable 'textoPlano'. Los parámetros son los siguientes: 
     * usuario: Usuario asignado para ingresar al WebService WSCFDBuilder.
     * password: Contraseña asignada para ingresar al WebService WSCFDBuilder.
     * id: Identificación fiscal de la empresa emisora del documento (RFC en México).
     * textoPlano: Texto plano según layout 3.60 de EdixCFD.
     * 
     * @param password
     * @param usuario
     * @param id
     * @param textoPlano
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://edixcfdisecure.ekomercio.com/procesarTextoPlano")
    @WebResult(name = "procesarTextoPlanoResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
    @RequestWrapper(localName = "procesarTextoPlano", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.ProcesarTextoPlano")
    @ResponseWrapper(localName = "procesarTextoPlanoResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.ProcesarTextoPlanoResponse")
    public String procesarTextoPlano(
        @WebParam(name = "usuario", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String usuario,
        @WebParam(name = "password", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String password,
        @WebParam(name = "id", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String id,
        @WebParam(name = "textoPlano", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String textoPlano);

    /**
     * Timbra un CFDI con base en el xml UTF8 en la variable 'xmlFirmado'. Devuelve el XML completo, timbrado. 
     * Los parámetros son los siguientes: 
     * usuario: Usuario asignado para ingresar al WebService WSCFDBuilder.
     * password: Contraseña asignada para ingresar al WebService WSCFDBuilder.
     * xmlFirmado: XML Firmado, sin timbrar, versión 3.0 según el Anexo 20.
     * email: Cuenta(s) de correo al que hace referencia el documento timbrado.
     * 
     * @param password
     * @param usuario
     * @param xmlFirmado
     * @param email
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "getCFDI_Email", action = "http://edixcfdisecure.ekomercio.com/getCFDI_Email")
    @WebResult(name = "getCFDI_EmailResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
    @RequestWrapper(localName = "getCFDI_Email", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.GetCFDIEmail")
    @ResponseWrapper(localName = "getCFDI_EmailResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.GetCFDIEmailResponse")
    public String getCFDIEmail(
        @WebParam(name = "usuario", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String usuario,
        @WebParam(name = "password", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String password,
        @WebParam(name = "xmlFirmado", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String xmlFirmado,
        @WebParam(name = "email", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String email);

    /**
     * Timbra un CFDI con base en el xml UTF8 en la variable 'xmlFirmado'. Devuelve el XML completo, timbrado. 
     * Los parámetros son los siguientes: 
     * usuario: Usuario asignado para ingresar al WebService WSCFDBuilder.
     * password: Contraseña asignada para ingresar al WebService WSCFDBuilder.
     * xmlFirmado: XML Firmado, sin timbrar, versión 3.0 según el Anexo 20.
     * 
     * @param password
     * @param usuario
     * @param xmlFirmado
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://edixcfdisecure.ekomercio.com/getCFDI")
    @WebResult(name = "getCFDIResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
    @RequestWrapper(localName = "getCFDI", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.GetCFDI")
    @ResponseWrapper(localName = "getCFDIResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.GetCFDIResponse")
    public String getCFDI(
        @WebParam(name = "usuario", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String usuario,
        @WebParam(name = "password", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String password,
        @WebParam(name = "xmlFirmado", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String xmlFirmado);

    /**
     * Firma y Timbra un CFDI con base en el xml UTF8 en la variable 'xmlFirmado'. Devuelve el XML completo, timbrado. 
     * Los parámetros son los siguientes: 
     * usuario: Usuario asignado para ingresar al WebService WSCFDBuilder.
     * password: Contraseña asignada para ingresar al WebService WSCFDBuilder.
     * xmlFirmado: XML Firmado, sin timbrar, versión 3.0 según el Anexo 20.
     * 
     * @param password
     * @param usuario
     * @param xmlFirmado
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "getCFDI_Sign", action = "http://edixcfdisecure.ekomercio.com/getCFDI_Sign")
    @WebResult(name = "getCFDI_SignResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
    @RequestWrapper(localName = "getCFDI_Sign", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.GetCFDISign")
    @ResponseWrapper(localName = "getCFDI_SignResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.GetCFDISignResponse")
    public String getCFDISign(
        @WebParam(name = "usuario", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String usuario,
        @WebParam(name = "password", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String password,
        @WebParam(name = "xmlFirmado", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String xmlFirmado);

    /**
     * Timbra un CFDI con base en el xml UTF8 en la variable 'xmlFirmado'. Devuelve el timbre. 
     * Los parámetros son los siguientes: 
     * usuario: Usuario asignado para ingresar al WebService WSCFDBuilder.
     * password: Contraseña asignada para ingresar al WebService WSCFDBuilder.
     * xmlFirmado: XML Firmado, sin timbrar, versión 3.0 según el Anexo 20.
     * 
     * @param password
     * @param usuario
     * @param xmlFirmado
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://edixcfdisecure.ekomercio.com/getTimbreCFDI")
    @WebResult(name = "getTimbreCFDIResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
    @RequestWrapper(localName = "getTimbreCFDI", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.GetTimbreCFDI")
    @ResponseWrapper(localName = "getTimbreCFDIResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.GetTimbreCFDIResponse")
    public String getTimbreCFDI(
        @WebParam(name = "usuario", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String usuario,
        @WebParam(name = "password", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String password,
        @WebParam(name = "xmlFirmado", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String xmlFirmado);

    /**
     * Cancela un UUID utilizando la información registrada por emisor en la base de datos de EdixCFD.
     * Los parámetros son los siguientes: 
     * usuario: Usuario asignado para ingresar al WebService WSCFDBuilder.
     * password: Contraseña asignada para ingresar al WebService WSCFDBuilder.
     * rfcEmisor: Identificación fiscal de la empresa emisora del documento.
     * 
     * 
     * @param password
     * @param usuario
     * @param uuid
     * @param rfcEmisor
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://edixcfdisecure.ekomercio.com/cancelarCFDI")
    @WebResult(name = "cancelarCFDIResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
    @RequestWrapper(localName = "cancelarCFDI", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.CancelarCFDI")
    @ResponseWrapper(localName = "cancelarCFDIResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.CancelarCFDIResponse")
    public String cancelarCFDI(
        @WebParam(name = "usuario", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String usuario,
        @WebParam(name = "password", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String password,
        @WebParam(name = "rfcEmisor", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String rfcEmisor,
        @WebParam(name = "uuid", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String uuid);

    /**
     * Anula (Cancela) ante la autoridad tributaria de Guatemala (SAT) una factura electrónica a través de la  recepción de una cadena de texto (Solicitud CAN).
     * Los parámetros son los siguientes: 
     *  1) usuario: Usuario asignado para ingresar al WebService WSCFDBuilder.
     *  2) password: Contraseña asignada para ingresar al WebService WSCFDBuilder.
     *  3) Id:Identificación fiscal de la empresa emisora del documento (NIT Emisor)
     *  4) TextoPlano: LayOut Archivo de solicitud de cancelación (.CAN)
     * 
     * 
     * @param password
     * @param usuario
     * @param nitEmisor
     * @param textoPlano
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://edixcfdisecure.ekomercio.com/anularFacturaGuatemala")
    @WebResult(name = "anularFacturaGuatemalaResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
    @RequestWrapper(localName = "anularFacturaGuatemala", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.AnularFacturaGuatemala")
    @ResponseWrapper(localName = "anularFacturaGuatemalaResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.AnularFacturaGuatemalaResponse")
    public String anularFacturaGuatemala(
        @WebParam(name = "usuario", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String usuario,
        @WebParam(name = "password", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String password,
        @WebParam(name = "nitEmisor", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String nitEmisor,
        @WebParam(name = "textoPlano", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String textoPlano);

    /**
     * Cancela unq retención utilizando la información registrada por emisor en la base de datos de EdixCFD.
     * Los parámetros son los siguientes: 
     * usuario: Usuario asignado para ingresar al WebService WSCFDBuilder.
     * password: Contraseña asignada para ingresar al WebService WSCFDBuilder.
     * rfcEmisor: Identificación fiscal de la empresa emisora del documento.
     * 
     * 
     * @param password
     * @param usuario
     * @param uuid
     * @param rfcEmisor
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://edixcfdisecure.ekomercio.com/cancelarRetencion")
    @WebResult(name = "cancelarRetencionResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
    @RequestWrapper(localName = "cancelarRetencion", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.CancelarRetencion")
    @ResponseWrapper(localName = "cancelarRetencionResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.CancelarRetencionResponse")
    public String cancelarRetencion(
        @WebParam(name = "usuario", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String usuario,
        @WebParam(name = "password", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String password,
        @WebParam(name = "rfcEmisor", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String rfcEmisor,
        @WebParam(name = "uuid", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String uuid);

    /**
     * 
     * @param cRFC
     * @param satValidarListaBlancaResult
     * @param cNumeroCertificado
     * @param cMensaje
     * @param dFechaFAK
     */
    @WebMethod(operationName = "SAT_ValidarListaBlanca", action = "http://edixcfdisecure.ekomercio.com/SAT_ValidarListaBlanca")
    @RequestWrapper(localName = "SAT_ValidarListaBlanca", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.SATValidarListaBlanca")
    @ResponseWrapper(localName = "SAT_ValidarListaBlancaResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.SATValidarListaBlancaResponse")
    public void satValidarListaBlanca(
        @WebParam(name = "cRFC", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String cRFC,
        @WebParam(name = "cNumeroCertificado", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String cNumeroCertificado,
        @WebParam(name = "dFechaFAK", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        XMLGregorianCalendar dFechaFAK,
        @WebParam(name = "cMensaje", targetNamespace = "http://edixcfdisecure.ekomercio.com/", mode = WebParam.Mode.INOUT)
        Holder<String> cMensaje,
        @WebParam(name = "SAT_ValidarListaBlancaResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/", mode = WebParam.Mode.OUT)
        Holder<Long> satValidarListaBlancaResult);

    /**
     * 
     * @param cRFC
     * @param cCertificadoBase64
     * @param nValidacionCertificado
     * @param cNumeroCertificado
     * @param satValidarCertificadoPropiosMediosResult
     * @param cMensaje
     */
    @WebMethod(operationName = "SAT_ValidarCertificadoPropiosMedios", action = "http://edixcfdisecure.ekomercio.com/SAT_ValidarCertificadoPropiosMedios")
    @RequestWrapper(localName = "SAT_ValidarCertificadoPropiosMedios", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.SATValidarCertificadoPropiosMedios")
    @ResponseWrapper(localName = "SAT_ValidarCertificadoPropiosMediosResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.SATValidarCertificadoPropiosMediosResponse")
    public void satValidarCertificadoPropiosMedios(
        @WebParam(name = "cRFC", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String cRFC,
        @WebParam(name = "cNumeroCertificado", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String cNumeroCertificado,
        @WebParam(name = "cCertificadoBase64", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String cCertificadoBase64,
        @WebParam(name = "nValidacionCertificado", targetNamespace = "http://edixcfdisecure.ekomercio.com/", mode = WebParam.Mode.INOUT)
        Holder<EnValidacionCertificado> nValidacionCertificado,
        @WebParam(name = "cMensaje", targetNamespace = "http://edixcfdisecure.ekomercio.com/", mode = WebParam.Mode.INOUT)
        Holder<String> cMensaje,
        @WebParam(name = "SAT_ValidarCertificadoPropiosMediosResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/", mode = WebParam.Mode.OUT)
        Holder<Boolean> satValidarCertificadoPropiosMediosResult);

    /**
     * 
     * @param dFechaDocumento
     * @param cRFC
     * @param cCertificadoBase64
     * @param satValidarCertificadoPropiosMediosFechaDocResult
     * @param nValidacionCertificado
     * @param cNumeroCertificado
     * @param cMensaje
     */
    @WebMethod(operationName = "SAT_ValidarCertificadoPropiosMediosFechaDoc", action = "http://edixcfdisecure.ekomercio.com/SAT_ValidarCertificadoPropiosMediosFechaDoc")
    @RequestWrapper(localName = "SAT_ValidarCertificadoPropiosMediosFechaDoc", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.SATValidarCertificadoPropiosMediosFechaDoc")
    @ResponseWrapper(localName = "SAT_ValidarCertificadoPropiosMediosFechaDocResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.SATValidarCertificadoPropiosMediosFechaDocResponse")
    public void satValidarCertificadoPropiosMediosFechaDoc(
        @WebParam(name = "cRFC", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String cRFC,
        @WebParam(name = "cNumeroCertificado", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String cNumeroCertificado,
        @WebParam(name = "cCertificadoBase64", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String cCertificadoBase64,
        @WebParam(name = "nValidacionCertificado", targetNamespace = "http://edixcfdisecure.ekomercio.com/", mode = WebParam.Mode.INOUT)
        Holder<EnValidacionCertificado> nValidacionCertificado,
        @WebParam(name = "cMensaje", targetNamespace = "http://edixcfdisecure.ekomercio.com/", mode = WebParam.Mode.INOUT)
        Holder<String> cMensaje,
        @WebParam(name = "dFechaDocumento", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        XMLGregorianCalendar dFechaDocumento,
        @WebParam(name = "SAT_ValidarCertificadoPropiosMediosFechaDocResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/", mode = WebParam.Mode.OUT)
        Holder<Boolean> satValidarCertificadoPropiosMediosFechaDocResult);

    /**
     * 
     * @param cRFC
     * @param oSerie
     * @param nAnoAprob
     * @param satConsecutivoDentroRangoResult
     * @param nFolio
     * @param nNumAprob
     * @param cMensaje
     */
    @WebMethod(operationName = "SAT_ConsecutivoDentroRango", action = "http://edixcfdisecure.ekomercio.com/SAT_ConsecutivoDentroRango")
    @RequestWrapper(localName = "SAT_ConsecutivoDentroRango", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.SATConsecutivoDentroRango")
    @ResponseWrapper(localName = "SAT_ConsecutivoDentroRangoResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.SATConsecutivoDentroRangoResponse")
    public void satConsecutivoDentroRango(
        @WebParam(name = "cRFC", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String cRFC,
        @WebParam(name = "oSerie", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        Object oSerie,
        @WebParam(name = "nFolio", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        long nFolio,
        @WebParam(name = "nAnoAprob", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        long nAnoAprob,
        @WebParam(name = "nNumAprob", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String nNumAprob,
        @WebParam(name = "cMensaje", targetNamespace = "http://edixcfdisecure.ekomercio.com/", mode = WebParam.Mode.INOUT)
        Holder<String> cMensaje,
        @WebParam(name = "SAT_ConsecutivoDentroRangoResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/", mode = WebParam.Mode.OUT)
        Holder<Boolean> satConsecutivoDentroRangoResult);

    /**
     * 
     * @param cRFC
     * @param cFechaFin
     * @param cNumCert
     * @param cFechaIni
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SATint_AgregarCertificadoParaFIEL", action = "http://edixcfdisecure.ekomercio.com/SATint_AgregarCertificadoParaFIEL")
    @WebResult(name = "SATint_AgregarCertificadoParaFIELResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
    @RequestWrapper(localName = "SATint_AgregarCertificadoParaFIEL", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.SATintAgregarCertificadoParaFIEL")
    @ResponseWrapper(localName = "SATint_AgregarCertificadoParaFIELResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.SATintAgregarCertificadoParaFIELResponse")
    public String saTintAgregarCertificadoParaFIEL(
        @WebParam(name = "cRFC", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String cRFC,
        @WebParam(name = "cNumCert", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String cNumCert,
        @WebParam(name = "cFechaIni", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String cFechaIni,
        @WebParam(name = "cFechaFin", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String cFechaFin);

    /**
     * Anula (cancela) una factura electrónica con base en el XML contenido
     * en la variable 'datosDocumentoXML'. Una vez anulado, emite la nota de crédito correspondiente. 
     * Los parámetros son los siguientes: 
     * usuario: Usuario asignado para ingresar al WebService WSCFDBuilder.
     * password: Contraseña asignada para ingresar al WebService WSCFDBuilder.
     * id: Identificación fiscal de la empresa emisora del documento (RFC en México).
     * datosDocumentoXML: Estructura con los datos del documento que se desea anular.
     * 
     * @param password
     * @param datosDocumentoXML
     * @param usuario
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://edixcfdisecure.ekomercio.com/anularDocumentoElectronicoXML")
    @WebResult(name = "anularDocumentoElectronicoXMLResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
    @RequestWrapper(localName = "anularDocumentoElectronicoXML", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.AnularDocumentoElectronicoXML")
    @ResponseWrapper(localName = "anularDocumentoElectronicoXMLResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.AnularDocumentoElectronicoXMLResponse")
    public String anularDocumentoElectronicoXML(
        @WebParam(name = "usuario", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String usuario,
        @WebParam(name = "password", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String password,
        @WebParam(name = "id", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String id,
        @WebParam(name = "datosDocumentoXML", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String datosDocumentoXML);

    /**
     * Anula (cancela) una factura electrónica con base en el XML contenido
     * en la variable 'datosDocumentoXML'. Devuelve el mismo documento anulado (cancelado). 
     * Los parámetros son los siguientes: 
     * usuario: Usuario asignado para ingresar al WebService WSCFDBuilder.
     * password: Contraseña asignada para ingresar al WebService WSCFDBuilder.
     * id: Identificación fiscal de la empresa emisora del documento (RFC en México).
     * datosDocumentoXML: Estructura con los datos del documento que se desea anular.
     * 
     * @param password
     * @param datosDocumentoXML
     * @param usuario
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "anularDocumentoElectronicoXML_SinNotaDeCredito", action = "http://edixcfdisecure.ekomercio.com/anularDocumentoElectronicoXML_SinNotaDeCredito")
    @WebResult(name = "anularDocumentoElectronicoXML_SinNotaDeCreditoResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
    @RequestWrapper(localName = "anularDocumentoElectronicoXML_SinNotaDeCredito", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.AnularDocumentoElectronicoXMLSinNotaDeCredito")
    @ResponseWrapper(localName = "anularDocumentoElectronicoXML_SinNotaDeCreditoResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.AnularDocumentoElectronicoXMLSinNotaDeCreditoResponse")
    public String anularDocumentoElectronicoXMLSinNotaDeCredito(
        @WebParam(name = "usuario", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String usuario,
        @WebParam(name = "password", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String password,
        @WebParam(name = "id", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String id,
        @WebParam(name = "datosDocumentoXML", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String datosDocumentoXML);

    /**
     * Valida y recibe un CFD ó CFDI con base en el xml UTF8 en la variable 'xmlFirmado'. Devuelve un acuse XML que indica el resultado. 
     * Los parámetros son los siguientes: 
     * usuario: Usuario asignado para ingresar al WebService WSCFDBuilder.
     * password: Contraseña asignada para ingresar al WebService WSCFDBuilder.
     * xmlFirmado: XML Firmado versión 2.x/3.x según el Anexo 20.
     * 
     * @param password
     * @param usuario
     * @param xmlFirmado
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://edixcfdisecure.ekomercio.com/receiveCFD")
    @WebResult(name = "receiveCFDResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
    @RequestWrapper(localName = "receiveCFD", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.ReceiveCFD")
    @ResponseWrapper(localName = "receiveCFDResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.ReceiveCFDResponse")
    public String receiveCFD(
        @WebParam(name = "usuario", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String usuario,
        @WebParam(name = "password", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String password,
        @WebParam(name = "xmlFirmado", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String xmlFirmado);

    /**
     * Convierte un archivo xml de propios medios CFD a un CFDI con base en el xml UTF8 en la variable 'xmlCFD'. Devuelve el XML completo 
     * Los parámetros son los siguientes: 
     * usuario: Usuario asignado para ingresar al WebService WSCFDBuilder.
     * password: Contraseña asignada para ingresar al WebService WSCFDBuilder.
     * xmlFile: XML, sin timbrar, versión 2.2 según el Anexo 20.
     * 
     * @param password
     * @param usuario
     * @param xmlCFD
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "getCFDI_FromCFD", action = "http://edixcfdisecure.ekomercio.com/getCFDI_FromCFD")
    @WebResult(name = "getCFDI_FromCFDResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
    @RequestWrapper(localName = "getCFDI_FromCFD", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.GetCFDIFromCFD")
    @ResponseWrapper(localName = "getCFDI_FromCFDResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.GetCFDIFromCFDResponse")
    public String getCFDIFromCFD(
        @WebParam(name = "usuario", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String usuario,
        @WebParam(name = "password", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String password,
        @WebParam(name = "xmlCFD", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String xmlCFD);

    /**
     * Genera la representación gráfica PDF de la factura en base a los documentos extraídos de datos de EdixCFD.
     * Los parámetros son los siguientes: 
     * usuario: Usuario asignado para ingresar al WebService WSCFDBuilder.
     * password: Contraseña asignada para ingresar al WebService WSCFDBuilder.
     * rfcEmisor: Identificación fiscal de la empresa emisora del documento.
     * uuid: Identificador unico del documento fiscal.
     * 
     * 
     * @param rfcemisor
     * @param password
     * @param usuario
     * @param uuid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://edixcfdisecure.ekomercio.com/generaPDF")
    @WebResult(name = "generaPDFResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
    @RequestWrapper(localName = "generaPDF", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.GeneraPDF")
    @ResponseWrapper(localName = "generaPDFResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.GeneraPDFResponse")
    public String generaPDF(
        @WebParam(name = "usuario", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String usuario,
        @WebParam(name = "password", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String password,
        @WebParam(name = "rfcemisor", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String rfcemisor,
        @WebParam(name = "uuid", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String uuid);

    /**
     * Convierte un archivo xml de propios medios CFD a un CFDI con base en el xml UTF8 en la variable 'xmlCFD'. Devuelve el XML completo 
     * Los parámetros son los siguientes: 
     * usuario: Usuario asignado para ingresar al WebService WSCFDBuilder.
     * password: Contraseña asignada para ingresar al WebService WSCFDBuilder.
     * xmlFile: XML, sin timbrar, versión 2.2 según el Anexo 20.
     * 
     * @param password
     * @param usuario
     * @param xmlCFD
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "getCFDI_FromCFDToken", action = "http://edixcfdisecure.ekomercio.com/getCFDI_FromCFDToken")
    @WebResult(name = "getCFDI_FromCFDTokenResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
    @RequestWrapper(localName = "getCFDI_FromCFDToken", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.GetCFDIFromCFDToken")
    @ResponseWrapper(localName = "getCFDI_FromCFDTokenResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.GetCFDIFromCFDTokenResponse")
    public String getCFDIFromCFDToken(
        @WebParam(name = "usuario", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String usuario,
        @WebParam(name = "password", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String password,
        @WebParam(name = "xmlCFD", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String xmlCFD);

    /**
     * 
     * @param oXMLDocument
     * @param cMensaje
     * @param satValidarComplementoNominaResult
     */
    @WebMethod(operationName = "SAT_ValidarComplementoNomina", action = "http://edixcfdisecure.ekomercio.com/SAT_ValidarComplementoNomina")
    @RequestWrapper(localName = "SAT_ValidarComplementoNomina", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.SATValidarComplementoNomina")
    @ResponseWrapper(localName = "SAT_ValidarComplementoNominaResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.SATValidarComplementoNominaResponse")
    public void satValidarComplementoNomina(
        @WebParam(name = "oXMLDocument", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        mx.com.mtlsa.billing.client.edixcfdisecure.SATValidarComplementoNomina.OXMLDocument oXMLDocument,
        @WebParam(name = "cMensaje", targetNamespace = "http://edixcfdisecure.ekomercio.com/", mode = WebParam.Mode.INOUT)
        Holder<String> cMensaje,
        @WebParam(name = "SAT_ValidarComplementoNominaResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/", mode = WebParam.Mode.OUT)
        Holder<Boolean> satValidarComplementoNominaResult);

    /**
     * 
     * @param cErrorMensaje
     * @param cConsecutivoInterno
     * @param existeConsecutivoInternoResult
     */
    @WebMethod(action = "http://edixcfdisecure.ekomercio.com/existeConsecutivoInterno")
    @RequestWrapper(localName = "existeConsecutivoInterno", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.ExisteConsecutivoInterno")
    @ResponseWrapper(localName = "existeConsecutivoInternoResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.ExisteConsecutivoInternoResponse")
    public void existeConsecutivoInterno(
        @WebParam(name = "cConsecutivoInterno", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String cConsecutivoInterno,
        @WebParam(name = "cErrorMensaje", targetNamespace = "http://edixcfdisecure.ekomercio.com/", mode = WebParam.Mode.INOUT)
        Holder<String> cErrorMensaje,
        @WebParam(name = "existeConsecutivoInternoResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/", mode = WebParam.Mode.OUT)
        Holder<Boolean> existeConsecutivoInternoResult);

    /**
     * Genera la representación gráfica PDF de los documentos recibidos en EdixCFD.
     * Los parámetros son los siguientes: 
     * usuario: Usuario asignado para ingresar al WebService WSCFDBuilder.
     * password: Contraseña asignada para ingresar al WebService WSCFDBuilder.
     * rfcReceptor: Identificación fiscal de la empresa receptora del documento.
     * uuid: Identificador unico del documento fiscal.
     * 
     * 
     * @param rfcReceptor
     * @param password
     * @param usuario
     * @param uuid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "generaPDF_Recepcion", action = "http://edixcfdisecure.ekomercio.com/generaPDF_Recepcion")
    @WebResult(name = "generaPDF_RecepcionResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
    @RequestWrapper(localName = "generaPDF_Recepcion", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.GeneraPDFRecepcion")
    @ResponseWrapper(localName = "generaPDF_RecepcionResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.GeneraPDFRecepcionResponse")
    public String generaPDFRecepcion(
        @WebParam(name = "usuario", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String usuario,
        @WebParam(name = "password", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String password,
        @WebParam(name = "rfcReceptor", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String rfcReceptor,
        @WebParam(name = "uuid", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String uuid);

    /**
     * Genera la representación gráfica PDF de los documentos emitidos en EdixCFD.
     * Los parámetros son los siguientes: 
     * usuario: Usuario asignado para ingresar al WebService WSCFDBuilder.
     * password: Contraseña asignada para ingresar al WebService WSCFDBuilder.
     * rfcEmisor: Identificación fiscal de la empresa emisora del documento.
     * uuid: Identificador unico del documento fiscal.
     * 
     * 
     * @param password
     * @param usuario
     * @param uuid
     * @param rfcEmisor
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "generaPDF_Envio", action = "http://edixcfdisecure.ekomercio.com/generaPDF_Envio")
    @WebResult(name = "generaPDF_EnvioResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
    @RequestWrapper(localName = "generaPDF_Envio", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.GeneraPDFEnvio")
    @ResponseWrapper(localName = "generaPDF_EnvioResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.GeneraPDFEnvioResponse")
    public String generaPDFEnvio(
        @WebParam(name = "usuario", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String usuario,
        @WebParam(name = "password", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String password,
        @WebParam(name = "rfcEmisor", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String rfcEmisor,
        @WebParam(name = "uuid", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String uuid);

    /**
     * 
     * @param oXMLDocument
     * @param satValidarComplementoNotariosPublicosResult
     * @param cMensaje
     */
    @WebMethod(operationName = "SAT_ValidarComplementoNotariosPublicos", action = "http://edixcfdisecure.ekomercio.com/SAT_ValidarComplementoNotariosPublicos")
    @RequestWrapper(localName = "SAT_ValidarComplementoNotariosPublicos", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.SATValidarComplementoNotariosPublicos")
    @ResponseWrapper(localName = "SAT_ValidarComplementoNotariosPublicosResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.SATValidarComplementoNotariosPublicosResponse")
    public void satValidarComplementoNotariosPublicos(
        @WebParam(name = "oXMLDocument", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        mx.com.mtlsa.billing.client.edixcfdisecure.SATValidarComplementoNotariosPublicos.OXMLDocument oXMLDocument,
        @WebParam(name = "cMensaje", targetNamespace = "http://edixcfdisecure.ekomercio.com/", mode = WebParam.Mode.INOUT)
        Holder<String> cMensaje,
        @WebParam(name = "SAT_ValidarComplementoNotariosPublicosResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/", mode = WebParam.Mode.OUT)
        Holder<Boolean> satValidarComplementoNotariosPublicosResult);

    /**
     * 
     * @param cSelloTimbre
     * @param satValidarTimbreResult
     * @param cCadenaOriginalTimbre
     * @param cNumeroCertificadoPAC
     * @param cMensaje
     */
    @WebMethod(operationName = "SAT_ValidarTimbre", action = "http://edixcfdisecure.ekomercio.com/SAT_ValidarTimbre")
    @RequestWrapper(localName = "SAT_ValidarTimbre", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.SATValidarTimbre")
    @ResponseWrapper(localName = "SAT_ValidarTimbreResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.SATValidarTimbreResponse")
    public void satValidarTimbre(
        @WebParam(name = "cCadenaOriginalTimbre", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String cCadenaOriginalTimbre,
        @WebParam(name = "cNumeroCertificadoPAC", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String cNumeroCertificadoPAC,
        @WebParam(name = "cSelloTimbre", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String cSelloTimbre,
        @WebParam(name = "cMensaje", targetNamespace = "http://edixcfdisecure.ekomercio.com/", mode = WebParam.Mode.INOUT)
        Holder<String> cMensaje,
        @WebParam(name = "SAT_ValidarTimbreResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/", mode = WebParam.Mode.OUT)
        Holder<Boolean> satValidarTimbreResult);

    /**
     * 
     * @param nMontoTotal
     * @param cRFCReceptor
     * @param cRFCEmisor
     * @param cUUID
     * @param satExisteTimbreSATResult
     * @param cMensaje
     */
    @WebMethod(operationName = "SAT_ExisteTimbreSAT", action = "http://edixcfdisecure.ekomercio.com/SAT_ExisteTimbreSAT")
    @RequestWrapper(localName = "SAT_ExisteTimbreSAT", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.SATExisteTimbreSAT")
    @ResponseWrapper(localName = "SAT_ExisteTimbreSATResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.SATExisteTimbreSATResponse")
    public void satExisteTimbreSAT(
        @WebParam(name = "cRFCEmisor", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String cRFCEmisor,
        @WebParam(name = "cRFCReceptor", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String cRFCReceptor,
        @WebParam(name = "nMontoTotal", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        BigDecimal nMontoTotal,
        @WebParam(name = "cUUID", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String cUUID,
        @WebParam(name = "cMensaje", targetNamespace = "http://edixcfdisecure.ekomercio.com/", mode = WebParam.Mode.INOUT)
        Holder<String> cMensaje,
        @WebParam(name = "SAT_ExisteTimbreSATResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/", mode = WebParam.Mode.OUT)
        Holder<Boolean> satExisteTimbreSATResult);

    /**
     * Genera una factura electrónica con base en el texto plano contenidoen la variable 'textoPlano'. Los parámetros son los siguientes: 
     * usuario: Usuario asignado para ingresar al WebService WSCFDBuilder.
     * password: Contraseña asignada para ingresar al WebService WSCFDBuilder.
     * id: Identificación fiscal de la empresa emisora del documento (RFC en México).
     * textoPlano: Texto plano según layout 3.60 de EdixCFD.
     * 
     * @param password
     * @param usuario
     * @param id
     * @param textoPlano
     * @return
     *     returns mx.com.mtlsa.billing.client.edixcfdisecure.ProcesarTextoPlanoToXMLResponse.ProcesarTextoPlanoToXMLResult
     */
    @WebMethod(action = "http://edixcfdisecure.ekomercio.com/procesarTextoPlanoToXML")
    @WebResult(name = "procesarTextoPlanoToXMLResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
    @RequestWrapper(localName = "procesarTextoPlanoToXML", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.ProcesarTextoPlanoToXML")
    @ResponseWrapper(localName = "procesarTextoPlanoToXMLResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.ProcesarTextoPlanoToXMLResponse")
    public mx.com.mtlsa.billing.client.edixcfdisecure.ProcesarTextoPlanoToXMLResponse.ProcesarTextoPlanoToXMLResult procesarTextoPlanoToXML(
        @WebParam(name = "usuario", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String usuario,
        @WebParam(name = "password", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String password,
        @WebParam(name = "id", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String id,
        @WebParam(name = "textoPlano", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String textoPlano);

    /**
     * Timbra un CFDI y genera adenda con base en el xml UTF8 en la variable 'xmlFirmado'. Devuelve el timbre. 
     * Los parámetros son los siguientes: 
     * usuario: Usuario asignado para ingresar al WebService WSCFDBuilder.
     * password: Contraseña asignada para ingresar al WebService WSCFDBuilder.
     * xmlFirmado: XML Firmado, sin timbrar, versión 3.0 según el Anexo 20.
     * 
     * @param password
     * @param usuario
     * @param xmlFirmado
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://edixcfdisecure.ekomercio.com/getTimbreCFDIaddendacomercial")
    @WebResult(name = "getTimbreCFDIaddendacomercialResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
    @RequestWrapper(localName = "getTimbreCFDIaddendacomercial", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.GetTimbreCFDIaddendacomercial")
    @ResponseWrapper(localName = "getTimbreCFDIaddendacomercialResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.GetTimbreCFDIaddendacomercialResponse")
    public String getTimbreCFDIaddendacomercial(
        @WebParam(name = "usuario", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String usuario,
        @WebParam(name = "password", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String password,
        @WebParam(name = "xmlFirmado", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String xmlFirmado);

    /**
     * Genera la consulta del acuse de envio proporcionado por la DIAN.
     * Los parámetros son los siguientes: 
     * <br/>*Usuario: Usuario asignado para ingresar al WebService WSCFDBuilder.
     * <br/>*Password: Contraseña asignada para ingresar al WebService WSCFDBuilder.
     * <br/>*NIT Emisor: Identificación fiscal de la empresa emisora del documento.
     * <br/>*Serie: Campo de control correspondiente al documento.
     * <br/>*Folio: Campo consecutivo de control correspondiente al documento.
     * <br/>*CUFE: Identificador unico del documento fiscal.
     * 
     * @param oBuscaAcuseDIAN
     * @return
     *     returns mx.com.mtlsa.billing.client.edixcfdisecure.ArrayOfClsRespuestaConsultaAcusesDIAN
     */
    @WebMethod(operationName = "acuseDIAN_Envio", action = "http://edixcfdisecure.ekomercio.com/acuseDIAN_Envio")
    @WebResult(name = "acuseDIAN_EnvioResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
    @RequestWrapper(localName = "acuseDIAN_Envio", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.AcuseDIANEnvio")
    @ResponseWrapper(localName = "acuseDIAN_EnvioResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.AcuseDIANEnvioResponse")
    public ArrayOfClsRespuestaConsultaAcusesDIAN acuseDIANEnvio(
        @WebParam(name = "oBuscaAcuseDIAN", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        ArrayOfClsListaConsultaAcusesDIAN oBuscaAcuseDIAN);

    /**
     * Genera la consulta del acuse de verificacion proporcionado por la DIAN.
     * Los parámetros son los siguientes: 
     * <br/>*Usuario: Usuario asignado para ingresar al WebService WSCFDBuilder.
     * <br/>*Password: Contraseña asignada para ingresar al WebService WSCFDBuilder.
     * <br/>*NIT Emisor: Identificación fiscal de la empresa emisora del documento.
     * <br/>*Serie: Campo de control correspondiente al documento.
     * <br/>*Folio: Campo consecutivo de control correspondiente al documento.
     * <br/>*CUFE: Identificador unico del documento fiscal.
     * 
     * 
     * @param oBuscaAcuseDIAN
     * @return
     *     returns mx.com.mtlsa.billing.client.edixcfdisecure.ArrayOfClsRespuestaConsultaAcusesDIAN
     */
    @WebMethod(operationName = "acuseDIAN_Verificacion", action = "http://edixcfdisecure.ekomercio.com/acuseDIAN_Verificacion")
    @WebResult(name = "acuseDIAN_VerificacionResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
    @RequestWrapper(localName = "acuseDIAN_Verificacion", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.AcuseDIANVerificacion")
    @ResponseWrapper(localName = "acuseDIAN_VerificacionResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.AcuseDIANVerificacionResponse")
    public ArrayOfClsRespuestaConsultaAcusesDIAN acuseDIANVerificacion(
        @WebParam(name = "oBuscaAcuseDIAN", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        ArrayOfClsListaConsultaAcusesDIAN oBuscaAcuseDIAN);

    /**
     * Timbra un CFDI con base en el xml UTF8 en la variable 'xmlFirmado'. Devuelve el XML completo, timbrado. 
     * Los parámetros son los siguientes: 
     * usuario: Usuario asignado para ingresar al WebService WSCFDBuilder.
     * password: Contraseña asignada para ingresar al WebService WSCFDBuilder.
     * xmlFirmado: XML Firmado, sin timbrar, versión 3.0 según el Anexo 20.
     * 
     * @param password
     * @param xmlBase64
     * @param usuario
     * @return
     *     returns mx.com.mtlsa.billing.client.edixcfdisecure.WSRespuestaTimbrado
     */
    @WebMethod(action = "http://edixcfdisecure.ekomercio.com/getCFDI2")
    @WebResult(name = "getCFDI2Result", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
    @RequestWrapper(localName = "getCFDI2", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.GetCFDI2")
    @ResponseWrapper(localName = "getCFDI2Response", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.GetCFDI2Response")
    public WSRespuestaTimbrado getCFDI2(
        @WebParam(name = "usuario", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String usuario,
        @WebParam(name = "password", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String password,
        @WebParam(name = "xmlBase64", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String xmlBase64);

    /**
     * Genera el reporte periodico de emisiones para las facturas. 
     * Los parámetros son los siguientes: 
     * usuario: Usuario asignado para ingresar al WebService WSCFDBuilder. 
     * Parámetro requerido password: Contraseña asignada para ingresar al WebService WSCFDBuilder. 
     * Parámetro requerido rfcemisor: RFC del Emisor para realizar la consulta. 
     * Parámetro requerido fechainicial: Fecha de inicio para la consulta de facturas. 
     * Parámetro requerido, con formato dd/MM/yyyy fechafinal: Fecha de fin para la consulta de facturas. 
     * Parámetro requerido, con formato dd/MM/yyyy rfcreceptor: RFC del Receptor para realizar la consulta. 
     * Parámetro opcional serie: Serie comprobante para la consulta de faturas. 
     * Parámetro opcional folioinicial: Rango de folio inicial para la consulta de facturas. 
     * Parámetro opcional foliofinal: Rango de folio final para la consulta de facturas. Parámetro opcional
     * 
     * @param rfcemisor
     * @param password
     * @param folioinicial
     * @param reportePeriodicoEmisionesResult
     * @param serie
     * @param foliofinal
     * @param cRetVal
     * @param fechainicial
     * @param cContenidoCSV
     * @param usuario
     * @param rfcreceptor
     * @param fechafinal
     */
    @WebMethod(action = "http://edixcfdisecure.ekomercio.com/reportePeriodicoEmisiones")
    @RequestWrapper(localName = "reportePeriodicoEmisiones", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.ReportePeriodicoEmisiones")
    @ResponseWrapper(localName = "reportePeriodicoEmisionesResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.ReportePeriodicoEmisionesResponse")
    public void reportePeriodicoEmisiones(
        @WebParam(name = "usuario", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String usuario,
        @WebParam(name = "password", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String password,
        @WebParam(name = "rfcemisor", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String rfcemisor,
        @WebParam(name = "fechainicial", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String fechainicial,
        @WebParam(name = "fechafinal", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String fechafinal,
        @WebParam(name = "rfcreceptor", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String rfcreceptor,
        @WebParam(name = "serie", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String serie,
        @WebParam(name = "folioinicial", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String folioinicial,
        @WebParam(name = "foliofinal", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String foliofinal,
        @WebParam(name = "cRetVal", targetNamespace = "http://edixcfdisecure.ekomercio.com/", mode = WebParam.Mode.INOUT)
        Holder<String> cRetVal,
        @WebParam(name = "cContenidoCSV", targetNamespace = "http://edixcfdisecure.ekomercio.com/", mode = WebParam.Mode.INOUT)
        Holder<String> cContenidoCSV,
        @WebParam(name = "reportePeriodicoEmisionesResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfEmision> reportePeriodicoEmisionesResult);

    /**
     * Método que obtiene la información si los RFCs consultados se encuentran en las Listas Negras identificado por Art69 y Art69B. 
     * Los parámetros son los siguientes: 
     * usuario: Usuario asignado para ingresar al WebService WSCFDBuilder. 
     * Parámetro requerido password: Contraseña asignada para ingresar al WebService WSCFDBuilder. 
     * Parámetro requerido rfcs: Lista de los Rfcs Emisores separados por coma en el caso de ser varios a consultar.
     * 
     * @param rfcs
     * @param password
     * @param usuario
     * @return
     *     returns mx.com.mtlsa.billing.client.edixcfdisecure.ResultadoListaNegra
     */
    @WebMethod(action = "http://edixcfdisecure.ekomercio.com/getListaNegra")
    @WebResult(name = "getListaNegraResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
    @RequestWrapper(localName = "getListaNegra", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.GetListaNegra")
    @ResponseWrapper(localName = "getListaNegraResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.GetListaNegraResponse")
    public ResultadoListaNegra getListaNegra(
        @WebParam(name = "usuario", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String usuario,
        @WebParam(name = "password", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String password,
        @WebParam(name = "rfcs", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String rfcs);

    /**
     * Método que obtiene la información detallada si los RFCs consultados se encuentran en las Listas Negras identificado por Art69 y Art69B. 
     * Los parámetros son los siguientes: 
     * usuario: Usuario asignado para ingresar al WebService WSCFDBuilder. 
     * Parámetro requerido password: Contraseña asignada para ingresar al WebService WSCFDBuilder. 
     * Parámetro requerido rfcs: Lista de los Rfcs Emisores separados por coma en el caso de ser varios a consultar.
     * 
     * @param rfcs
     * @param password
     * @param usuario
     * @return
     *     returns mx.com.mtlsa.billing.client.edixcfdisecure.ResultadoListaNegraDetalle
     */
    @WebMethod(action = "http://edixcfdisecure.ekomercio.com/getListaNegraDetalle")
    @WebResult(name = "getListaNegraDetalleResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
    @RequestWrapper(localName = "getListaNegraDetalle", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.GetListaNegraDetalle")
    @ResponseWrapper(localName = "getListaNegraDetalleResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.GetListaNegraDetalleResponse")
    public ResultadoListaNegraDetalle getListaNegraDetalle(
        @WebParam(name = "usuario", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String usuario,
        @WebParam(name = "password", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String password,
        @WebParam(name = "rfcs", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String rfcs);

    /**
     * Genera el reporte Timbrado. 
     * Los parámetros son los siguientes: 
     * Parámetro requerido cUsuario : Usuario asignado para ingresar al WebService WSCFDBuilder. 
     * Parámetro requerido cPassword : Contraseña asignada para ingresar al WebService WSCFDBuilder. 
     * Parámetro requerido cRFCEmisor : RFC del Emisor para realizar la consulta. 
     * Parámetro opcional cRFCReceptor : RFC del Receptor para realizar la consulta. 
     * Parámetro opcional cRazonSocialReceptor: Razón social del receptor
     * Parámetro opcional serie: Serie comprobante para la consulta de faturas. 
     * Parámetro opcional folioinicial: Rango de folio inicial para la consulta de facturas. 
     * Parámetro requerido, con formato dd/MM/yyyy dFechaInicioTimbrado : Fecha de inicio para la consulta de facturas. 
     * Parámetro requerido, con formato dd/MM/yyyy dFechaFinTimbrado : Fecha de fin para la consulta de facturas. 
     * 
     * 
     * @param cRFCReceptor
     * @param cRFCEmisor
     * @param cPassword
     * @param cSerie
     * @param cFolio
     * @param fechainicial
     * @param cUsuario
     * @param fechafinal
     * @param cRazonSocialReceptor
     * @return
     *     returns mx.com.mtlsa.billing.client.edixcfdisecure.ReporteTimbradoResult
     */
    @WebMethod(operationName = "ReporteTimbrado", action = "http://edixcfdisecure.ekomercio.com/ReporteTimbrado")
    @WebResult(name = "ReporteTimbradoResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
    @RequestWrapper(localName = "ReporteTimbrado", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.ReporteTimbrado")
    @ResponseWrapper(localName = "ReporteTimbradoResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.ReporteTimbradoResponse")
    public ReporteTimbradoResult reporteTimbrado(
        @WebParam(name = "cUsuario", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String cUsuario,
        @WebParam(name = "cPassword", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String cPassword,
        @WebParam(name = "cRFCEmisor", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String cRFCEmisor,
        @WebParam(name = "cRFCReceptor", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String cRFCReceptor,
        @WebParam(name = "cRazonSocialReceptor", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String cRazonSocialReceptor,
        @WebParam(name = "cSerie", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String cSerie,
        @WebParam(name = "cFolio", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String cFolio,
        @WebParam(name = "fechainicial", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String fechainicial,
        @WebParam(name = "fechafinal", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String fechafinal);

    /**
     * Timbra un CFDI con base en el xml UTF8 sin firmar en la variable 'xmlSinFirma'. Devuelve el XML completo, timbrado en formato normal y su PDF en formato base64 
     * Los parámetros son los siguientes: 
     * usuario: Usuario asignado para ingresar al WebService WSCFDBuilder.
     * password: Contraseña asignada para ingresar al WebService WSCFDBuilder.
     * xmlSinFirma: XML sin Firma, sin timbrar, versión 3.0 según el Anexo 20.
     * 
     * @param password
     * @param usuario
     * @param xmlSinFirma
     * @return
     *     returns mx.com.mtlsa.billing.client.edixcfdisecure.ResponseXMLPDF
     */
    @WebMethod(action = "http://edixcfdisecure.ekomercio.com/getTimbrePDF")
    @WebResult(name = "getTimbrePDFResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
    @RequestWrapper(localName = "getTimbrePDF", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.GetTimbrePDF")
    @ResponseWrapper(localName = "getTimbrePDFResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.GetTimbrePDFResponse")
    public ResponseXMLPDF getTimbrePDF(
        @WebParam(name = "usuario", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String usuario,
        @WebParam(name = "password", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String password,
        @WebParam(name = "xmlSinFirma", targetNamespace = "http://edixcfdisecure.ekomercio.com/")
        String xmlSinFirma);

    /**
     * 
     * @param validarFuncionamientoResult
     * @param cMensaje
     */
    @WebMethod(operationName = "ValidarFuncionamiento", action = "http://edixcfdisecure.ekomercio.com/ValidarFuncionamiento")
    @RequestWrapper(localName = "ValidarFuncionamiento", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.ValidarFuncionamiento")
    @ResponseWrapper(localName = "ValidarFuncionamientoResponse", targetNamespace = "http://edixcfdisecure.ekomercio.com/", className = "mx.com.mtlsa.billing.client.edixcfdisecure.ValidarFuncionamientoResponse")
    public void validarFuncionamiento(
        @WebParam(name = "cMensaje", targetNamespace = "http://edixcfdisecure.ekomercio.com/", mode = WebParam.Mode.INOUT)
        Holder<String> cMensaje,
        @WebParam(name = "ValidarFuncionamientoResult", targetNamespace = "http://edixcfdisecure.ekomercio.com/", mode = WebParam.Mode.OUT)
        Holder<Boolean> validarFuncionamientoResult);

}
